/*
 * StarCG gather best-spot data (採集最佳點).
 * Source:        https://guide.starcg.net/production/best-spots
 * Fetched:       2026-10-03T02:38:52Z
 * Last-Modified: 2026-10-01T13:28:05Z
 * Content:       73 items, 151 spots; minutes = average time to gather 4000 items (5-10 min error)
 *
 * GENERATED by scripts/sync-gather-data.mjs, DO NOT EDIT BY HAND.
 * Regenerate with: node scripts/sync-gather-data.mjs
 */
(function (root) {
  var data = {
    "version": 1,
    "fetchedAt": 1790995132855,
    "lastModified": "2026-10-01T13:28:05Z",
    "source": "https://guide.starcg.net/production/best-spots",
    "benchmark": {"items":4000,"slotSize":800,"slots":5},
    "aliases": {},
    "categories": [
      {"key": "hunt", "label": "狩獵", "items": [
        {"key":"hunt/小麥粉","name":"小麥粉","level":1,"fee4000":1320,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":133},{"key":"p:米內葛爾島坎村西南門外","place":"米內葛爾島 坎村西南門外","kind":"spot","minutes":135,"coords":[602,366]}]},
        {"key":"hunt/鹿皮","name":"鹿皮","level":1,"fee4000":1320,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":133},{"key":"p:芙蕾雅亞留特村東門外","place":"芙蕾雅 亞留特村東門外","kind":"spot","minutes":141,"coords":[648,180]}]},
        {"key":"hunt/雞蛋","name":"雞蛋","level":1,"fee4000":1320,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":134},{"key":"p:米內葛爾島坎村北門外","place":"米內葛爾島 坎村北門外","kind":"spot","minutes":134,"coords":[600,240]}]},
        {"key":"hunt/神聖米","name":"神聖米","level":1,"fee4000":1320,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":135},{"key":"p:艾爾沙島西門外溫迪爾平原","place":"艾爾沙島西門外 溫迪爾平原","kind":"spot","minutes":134,"coords":[191,41]}]},
        {"key":"hunt/青椒","name":"青椒","level":2,"fee4000":2000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":151},{"key":"p:芙蕾雅伊爾村外","place":"芙蕾雅 伊爾村外","kind":"mixed","minutes":null,"coords":[590,289],"nav":true}]},
        {"key":"hunt/蔥","name":"蔥","level":2,"fee4000":2000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":149},{"key":"p:布拉基姆高地艾夏島東門外","place":"布拉基姆高地 艾夏島東門外","kind":"spot","minutes":148,"coords":[74,186]}]},
        {"key":"hunt/牛奶","name":"牛奶","level":2,"fee4000":2000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":149},{"key":"p:米內葛爾島坎那貝拉村南門外","place":"米內葛爾島 坎那貝拉村南門外","kind":"spot","minutes":149,"coords":[590,370]}]},
        {"key":"hunt/大豆","name":"大豆","level":2,"fee4000":2000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":167},{"key":"p:法蘭城遺跡","place":"法蘭城遺跡","kind":"spot","minutes":149,"coords":[111,54]}]},
        {"key":"hunt/鹽","name":"鹽","level":3,"fee4000":2520,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":167},{"key":"p:米內葛爾島坎村南門外","place":"米內葛爾島 坎村南門外","kind":"spot","minutes":169,"coords":[709,360]}]},
        {"key":"hunt/醬油","name":"醬油","level":3,"fee4000":2520,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":168},{"key":"p:德威特島摩頓村外","place":"德威特島 摩頓村外","kind":"spot","minutes":133,"coords":[340,561]}]},
        {"key":"hunt/雞肉","name":"雞肉","level":4,"fee4000":3080,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":190},{"key":"p:庫魯克斯島哥拉爾鎮北門外","place":"庫魯克斯島 哥拉爾鎮北門外","kind":"spot","minutes":192,"coords":[266,378]}]},
        {"key":"hunt/芹菜","name":"芹菜","level":4,"fee4000":3080,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":189},{"key":"p:芙蕾雅亞留特村東門外","place":"芙蕾雅 亞留特村東門外","kind":"spot","minutes":209,"coords":[603,64],"nav":true}]},
        {"key":"hunt/竹筍","name":"竹筍","level":4,"fee4000":3080,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":192},{"key":"p:芙蕾雅亞留特村北門外","place":"芙蕾雅 亞留特村北門外","kind":"spot","minutes":226,"coords":[533,41],"nav":true}]},
        {"key":"hunt/海苔","name":"海苔","level":4,"fee4000":3080,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":192},{"key":"p:芙蕾雅亞留特村北門外","place":"芙蕾雅 亞留特村北門外","kind":"spot","minutes":133,"coords":[621,27]}]},
        {"key":"hunt/牛肉","name":"牛肉","level":5,"fee4000":4000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":267},{"key":"p:索奇亞奇利村東門外","place":"索奇亞 奇利村東門外","kind":"spot","minutes":200,"coords":[354,364],"nav":true}]},
        {"key":"hunt/星鰻","name":"星鰻","level":5,"fee4000":4000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":269},{"key":"p:芙蕾雅維諾亞村外","place":"芙蕾雅 維諾亞村外","kind":"spot","minutes":268,"coords":[425,466],"nav":true}]},
        {"key":"hunt/薑","name":"薑","level":5,"fee4000":4000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":267},{"key":"p:索奇亞奇利村東門外","place":"索奇亞 奇利村東門外","kind":"spot","minutes":267,"coords":[415,298],"nav":true}]},
        {"key":"hunt/馬鈴薯","name":"馬鈴薯","level":5,"fee4000":4000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":265},{"key":"p:庫魯克斯島魯米那斯村外","place":"庫魯克斯島 魯米那斯村外","kind":"spot","minutes":225,"coords":[260,870]},{"key":"p:布拉基姆高地艾夏島東門外","place":"布拉基姆高地 艾夏島東門外","kind":"spot","minutes":190,"coords":[176,233]}]},
        {"key":"hunt/胡椒","name":"胡椒","level":5,"fee4000":4000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":221},{"key":"p:庫魯克斯島米諾基亞鎮東門外","place":"庫魯克斯島 米諾基亞鎮東門外","kind":"spot","minutes":223,"coords":[550,860]},{"key":"p:光之路","place":"光之路","kind":"spot","minutes":219,"coords":[201,18]}]},
        {"key":"hunt/米","name":"米","level":6,"fee4000":5320,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":267},{"key":"p:索奇亞加納村外","place":"索奇亞 加納村外","kind":"spot","minutes":331,"coords":[626,304]}]},
        {"key":"hunt/砂糖","name":"砂糖","level":6,"fee4000":5320,"hint":"💡 建議到維諾亞村村長家最裡面房屋購買 (4G/個)，自己買工時採集平均約 4.2G/個，還需負擔時間成本！","spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":460},{"key":"p:莎蓮娜魔法大學裡面","place":"莎蓮娜 魔法大學裡面","kind":"spot","minutes":465,"coords":[85,46]}]},
        {"key":"hunt/咖哩塊","name":"咖哩塊","level":7,"fee4000":8000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":335},{"key":"p:莎蓮娜傑諾瓦鎮東門外","place":"莎蓮娜 傑諾瓦鎮東門外","kind":"spot","minutes":454,"coords":[270,426],"nav":true},{"key":"p:布拉基姆高地需從梅布爾隘地去","place":"布拉基姆高地 需從梅布爾隘地去","kind":"spot","minutes":209,"coords":[131,224]}]},
        {"key":"hunt/辣椒","name":"辣椒","level":7,"fee4000":8000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":335},{"key":"p:庫魯克斯島哥拉爾東門外","place":"庫魯克斯島 哥拉爾東門外","kind":"spot","minutes":338,"coords":[321,367]}]},
        {"key":"hunt/高級奶油","name":"高級奶油","level":7,"fee4000":8000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":444},{"key":"p:庫魯克斯島橋南後","place":"庫魯克斯島 橋南後","kind":"spot","minutes":333,"coords":[476,666]}]},
        {"key":"hunt/霜降牛肉","name":"霜降牛肉","level":8,"fee4000":11440,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":677},{"key":"p:庫魯克斯島哥拉爾鎮東門外","place":"庫魯克斯島 哥拉爾鎮東門外","kind":"spot","minutes":446,"coords":[419,450]},{"key":"p:米內葛爾島坎那貝拉村南門外","place":"米內葛爾島 坎那貝拉村南門外","kind":"spot","minutes":444,"coords":[604,421]}]},
        {"key":"hunt/阿巴尼斯哈蜜瓜","name":"阿巴尼斯哈蜜瓜","level":8,"fee4000":11440,"hint":null,"spots":[{"key":"p:莎蓮娜阿巴尼斯村外","place":"莎蓮娜 阿巴尼斯村外","kind":"unique","minutes":null,"coords":[88,74]}]},
        {"key":"hunt/螃蟹","name":"螃蟹","level":8,"fee4000":11440,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":452},{"key":"p:莎蓮娜傑諾瓦鎮東門外","place":"莎蓮娜 傑諾瓦鎮東門外","kind":"spot","minutes":445,"coords":[318,503]}]},
        {"key":"hunt/溼地毒蛇","name":"溼地毒蛇","level":8,"fee4000":11440,"hint":null,"spots":[{"key":"p:莎蓮娜魔法大學地底湖地下2F的小島","place":"莎蓮娜 魔法大學 地底湖地下 2F 的小島","kind":"unique","minutes":null,"coords":[37,49]}]},
        {"key":"hunt/伊勢蝦","name":"伊勢蝦","level":9,"fee4000":18200,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":661},{"key":"p:庫魯克斯島哥拉爾鎮西門外","place":"庫魯克斯島 哥拉爾鎮西門外","kind":"spot","minutes":669,"coords":[147,400],"nav":true}]},
        {"key":"hunt/海膽","name":"海膽","level":9,"fee4000":18200,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":664},{"key":"p:庫魯克斯島哥拉爾鎮西門外","place":"庫魯克斯島 哥拉爾鎮西門外","kind":"spot","minutes":665,"coords":[163,411],"nav":true}]},
        {"key":"hunt/魚翅","name":"魚翅","level":10,"fee4000":40000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":1337},{"key":"p:庫魯克斯島哥拉爾鎮東門外","place":"庫魯克斯島 哥拉爾鎮東門外","kind":"spot","minutes":1434,"coords":[390,530],"nav":true}]},
        {"key":"hunt/鱉","name":"鱉","level":10,"fee4000":40000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":1325},{"key":"p:庫魯克斯島哥拉爾鎮北門外","place":"庫魯克斯島 哥拉爾鎮北門外","kind":"spot","minutes":1378,"coords":[298,291],"nav":true}]}
      ]},
      {"key": "mine", "label": "挖掘", "items": [
        {"key":"mine/銅","name":"銅","level":1,"fee4000":1320,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":134},{"key":"p:芙蕾雅法蘭城西門外國營第24坑道B1","place":"芙蕾雅 法蘭城西門外 國營第 24 坑道 B1","kind":"spot","minutes":135,"coords":[12,29],"nav":true}]},
        {"key":"mine/鐵","name":"鐵","level":2,"fee4000":2000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":149},{"key":"p:芙蕾雅法蘭城西門外國營第24坑道B4B3往東北到B4","place":"芙蕾雅 法蘭城西門外 國營第24坑道B4 B3往東北到B4","kind":"spot","minutes":134,"coords":[33,31],"note":"任務 礦工的安全帽"}]},
        {"key":"mine/銀","name":"銀","level":3,"fee4000":2520,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":169},{"key":"p:芙蕾雅法蘭城西門外國營第24坑道B4B3往西北到B4","place":"芙蕾雅 法蘭城西門外 國營第24坑道B4 B3往西北到B4","kind":"spot","minutes":134,"coords":[27,21],"note":"任務 礦工的安全帽"}]},
        {"key":"mine/鋁","name":"鋁","level":3,"fee4000":2520,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":190},{"key":"p:艾夏島東門外布拉基姆高地黑歷史之石洞第一層","place":"艾夏島東門外 布拉基姆高地 黑歷史之石洞第一層","kind":"spot","minutes":186,"coords":[163,191]}]},
        {"key":"mine/純銀","name":"純銀","level":4,"fee4000":3080,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":189},{"key":"p:芙蕾雅亞留特村東門外哈巴魯東邊洞窟地下1樓","place":"芙蕾雅 亞留特村東門外 哈巴魯東邊洞窟地下 1 樓","kind":"spot","minutes":224,"coords":[14,14],"nav":true},{"key":"p:艾夏島東門外布拉基姆高地過瀑布後","place":"艾夏島東門外 布拉基姆高地 過瀑布後","kind":"spot","minutes":167,"coords":[267,301]}]},
        {"key":"mine/金","name":"金","level":5,"fee4000":4000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":223},{"key":"p:芙蕾雅亞留特村東門外哈巴魯東邊洞窟地下1樓","place":"芙蕾雅 亞留特村東門外 哈巴魯東邊洞窟地下 1 樓","kind":"spot","minutes":269,"coords":[42,10],"nav":true},{"key":"p:艾夏島東門外布拉基姆高地過瀑布後","place":"艾夏島東門外 布拉基姆高地 過瀑布後","kind":"spot","minutes":190,"coords":[261,255]}]},
        {"key":"mine/白金","name":"白金","level":6,"fee4000":5320,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":268},{"key":"p:索奇亞奇利村北門外海洞地下2樓","place":"索奇亞 奇利村北門外 海洞地下 2 樓","kind":"spot","minutes":333,"coords":[20,17],"nav":true,"note":"旁邊"}]},
        {"key":"mine/鋼騎之礦","name":"鋼騎之礦","level":6,"fee4000":5320,"hint":null,"spots":[{"key":"p:海賊的礦山全域","place":"海賊的礦山全域","kind":"unique","minutes":null,"note":"任務 海賊的寶地；隨機掉落"}]},
        {"key":"mine/幻之鋼","name":"幻之鋼","level":7,"fee4000":8000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":335},{"key":"p:莎蓮娜傑諾瓦鎮西門外莎蓮娜海洞地下2樓","place":"莎蓮娜 傑諾瓦鎮西門外 莎蓮娜海洞地下 2 樓","kind":"spot","minutes":451,"coords":[12,6],"nav":true}]},
        {"key":"mine/幻之銀","name":"幻之銀","level":8,"fee4000":11440,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":444},{"key":"p:索奇亞奇利村北門外海洞地下2樓","place":"索奇亞 奇利村北門外 海洞地下 2 樓","kind":"spot","minutes":663,"coords":[33,15],"nav":true}]},
        {"key":"mine/藍龍之鱗","name":"藍龍之鱗","level":8,"fee4000":11440,"hint":null,"spots":[{"key":"p:莎蓮娜魔法大學青龍的洞窟頂層青龍之巢","place":"莎蓮娜 魔法大學 青龍的洞窟 頂層青龍之巢","kind":"unique","minutes":null,"coords":[63,36]}]},
        {"key":"mine/永久冰石","name":"永久冰石","level":8,"fee4000":11440,"hint":null,"spots":[{"key":"p:莎蓮娜魔法大學青龍的洞窟地下2樓","place":"莎蓮娜 魔法大學 青龍的洞窟 地下 2 樓","kind":"unique","minutes":null,"coords":[20,21]}]},
        {"key":"mine/達馬斯礦","name":"達馬斯礦","level":8,"fee4000":11440,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":191},{"key":"p:米內葛爾島阿凱魯法村南門外南恰拉山第一通道","place":"米內葛爾島 阿凱魯法村南門外 南恰拉山第一通道","kind":"spot","minutes":438,"coords":[9,33]}]},
        {"key":"mine/勒格耐席鉧","name":"勒格耐席鉧","level":9,"fee4000":18200,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":669},{"key":"p:莎蓮娜傑諾瓦鎮西門外西方洞窟地下1樓","place":"莎蓮娜 傑諾瓦鎮西門外 西方洞窟地下 1 樓","kind":"spot","minutes":1344,"coords":[21,27],"nav":true}]},
        {"key":"mine/謝爾哈特礦","name":"謝爾哈特礦","level":9,"fee4000":18200,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":670},{"key":"p:米內葛爾島坎那貝拉村西門外海底通道1樓","place":"米內葛爾島 坎那貝拉村西門外 海底通道 1 樓","kind":"spot","minutes":670,"coords":[37,40]}]},
        {"key":"mine/喜馬拉斯礦","name":"喜馬拉斯礦","level":10,"fee4000":40000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":1453},{"key":"p:庫魯克斯島米諾基亞鎮西門外伊利斯礦山大坑道","place":"庫魯克斯島 米諾基亞鎮西門外 伊利斯礦山大坑道","kind":"mixed","minutes":null,"coords":[118,125]}]},
        {"key":"mine/奧利哈鋼","name":"奧利哈鋼","level":10,"fee4000":40000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":1237},{"key":"p:莎蓮娜傑諾瓦鎮西門外西方洞窟地下2樓","place":"莎蓮娜 傑諾瓦鎮西門外 西方洞窟地下 2 樓","kind":"spot","minutes":2814,"coords":[49,50],"nav":true}]}
      ]},
      {"key": "wood", "label": "木材", "items": [
        {"key":"wood/印度輕木","name":"印度輕木","level":1,"fee4000":1320,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":133},{"key":"p:芙蕾雅法蘭城東門外","place":"芙蕾雅 法蘭城東門外","kind":"spot","minutes":133,"coords":[491,197],"nav":true}]},
        {"key":"wood/樅","name":"樅","level":2,"fee4000":2000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":133},{"key":"p:芙蕾雅法蘭城西門外","place":"芙蕾雅 法蘭城西門外","kind":"spot","minutes":146,"coords":[451,163],"nav":true}]},
        {"key":"wood/黃月木","name":"黃月木","level":3,"fee4000":2520,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":167},{"key":"p:索奇亞奇利村東門外","place":"索奇亞 奇利村東門外","kind":"spot","minutes":192,"coords":[295,325],"nav":true}]},
        {"key":"wood/鐵杉","name":"鐵杉","level":4,"fee4000":3080,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":191},{"key":"p:庫魯克斯島哥拉爾鎮東門外","place":"庫魯克斯島 哥拉爾鎮東門外","kind":"spot","minutes":190,"coords":[485,537],"nav":true}]},
        {"key":"wood/琵琶木","name":"琵琶木","level":5,"fee4000":4000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":222},{"key":"p:米內葛爾島阿凱魯法村南門外","place":"米內葛爾島 阿凱魯法村南門外","kind":"spot","minutes":222,"coords":[203,346],"nav":true}]},
        {"key":"wood/茱萸木","name":"茱萸木","level":5,"fee4000":4000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":191},{"key":"p:艾爾莎島北門外蓋雷布倫森林","place":"艾爾莎島北門外 蓋雷布倫森林","kind":"spot","minutes":191,"coords":[187,43]}]},
        {"key":"wood/赤松","name":"赤松","level":6,"fee4000":5320,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":271},{"key":"p:米內葛爾島阿凱魯法村南門外","place":"米內葛爾島 阿凱魯法村南門外","kind":"spot","minutes":267,"coords":[192,375],"nav":true}]},
        {"key":"wood/樸","name":"樸","level":7,"fee4000":8000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":335},{"key":"p:米內葛爾島阿凱魯法村南門外","place":"米內葛爾島 阿凱魯法村南門外","kind":"spot","minutes":333,"coords":[170,460],"nav":true}]},
        {"key":"wood/杉","name":"杉","level":8,"fee4000":11440,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":449},{"key":"p:米內葛爾島坎那貝拉村南門外","place":"米內葛爾島 坎那貝拉村南門外","kind":"spot","minutes":445,"coords":[580,325],"nav":true}]},
        {"key":"wood/單木","name":"單木","level":8,"fee4000":11440,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":189},{"key":"p:米內葛爾島阿凱魯法南門外","place":"米內葛爾島 阿凱魯法南門外","kind":"spot","minutes":270,"coords":[234,425]}]},
        {"key":"wood/絲柏","name":"絲柏","level":9,"fee4000":18200,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":675},{"key":"p:庫魯克斯島橋南後紳士淑女養成所","place":"庫魯克斯島 橋南後 紳士淑女養成所","kind":"spot","minutes":671,"coords":[349,591],"nav":true}]},
        {"key":"wood/梣","name":"梣","level":10,"fee4000":40000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":1326},{"key":"p:庫魯克斯島米諾基亞鎮東門外","place":"庫魯克斯島 米諾基亞鎮東門外","kind":"spot","minutes":1340,"coords":[501,723],"nav":true}]}
      ]},
      {"key": "herb", "label": "花草", "items": [
        {"key":"herb/蘋果薄荷","name":"蘋果薄荷","level":1,"fee4000":1320,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":138},{"key":"p:芙蕾雅法蘭城西門外","place":"芙蕾雅 法蘭城西門外","kind":"spot","minutes":133,"coords":[500,85],"nav":true}]},
        {"key":"herb/檸檬草","name":"檸檬草","level":2,"fee4000":2000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":154},{"key":"p:芙蕾雅法蘭城西門外","place":"芙蕾雅 法蘭城西門外","kind":"spot","minutes":167,"coords":[515,100],"nav":true}]},
        {"key":"herb/蝴蝶花","name":"蝴蝶花","level":3,"fee4000":2520,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":167},{"key":"p:芙蕾雅法蘭城西門外","place":"芙蕾雅 法蘭城西門外","kind":"spot","minutes":193,"coords":[505,120],"nav":true}]},
        {"key":"herb/果梨","name":"果梨","level":4,"fee4000":3080,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":193},{"key":"p:庫魯克斯島米諾基亞鎮東門外","place":"庫魯克斯島 米諾基亞鎮東門外","kind":"spot","minutes":198,"coords":[601,705]},{"key":"p:庫魯克斯島麥尼村外","place":"庫魯克斯島 麥尼村外","kind":"spot","minutes":198,"coords":[432,681]}]},
        {"key":"herb/桃木","name":"桃木","level":5,"fee4000":4000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":226},{"key":"p:庫魯克斯島米諾基亞鎮東門外","place":"庫魯克斯島 米諾基亞鎮東門外","kind":"spot","minutes":224,"coords":[562,792]}]},
        {"key":"herb/番紅花","name":"番紅花","level":6,"fee4000":5320,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":267},{"key":"p:光之路","place":"光之路","kind":"spot","minutes":267,"coords":[240,90]},{"key":"p:庫魯克斯島哥拉爾鎮北門外","place":"庫魯克斯島 哥拉爾鎮北門外","kind":"spot","minutes":268,"coords":[202,350]}]},
        {"key":"herb/百里香","name":"百里香","level":7,"fee4000":8000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":336},{"key":"p:光之路","place":"光之路","kind":"spot","minutes":337,"coords":[173,85]},{"key":"p:庫魯克斯島哥拉爾鎮東門外","place":"庫魯克斯島 哥拉爾鎮東門外","kind":"spot","minutes":340,"coords":[474,409]}]},
        {"key":"herb/香草","name":"香草","level":8,"fee4000":11440,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":454},{"key":"p:米內葛爾島坎那貝拉村西門外","place":"米內葛爾島 坎那貝拉村西門外","kind":"spot","minutes":443,"coords":[476,241]},{"key":"p:庫魯克斯島橋北上方","place":"庫魯克斯島 橋北上方","kind":"spot","minutes":443,"coords":[508,508],"nav":true}]},
        {"key":"herb/瞿麥","name":"瞿麥","level":8,"fee4000":11440,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":444},{"key":"p:光之路","place":"光之路","kind":"spot","minutes":446,"coords":[157,115]},{"key":"p:庫魯克斯島橋南後","place":"庫魯克斯島 橋南後","kind":"spot","minutes":448,"coords":[446,569]}]},
        {"key":"herb/魔法紅蘿卜","name":"魔法紅蘿卜","level":8,"fee4000":11440,"hint":"💡 於魔法大學(117, 164)倉庫內與葛德雷翁以 500G 購買魔法手套，能增加採集量。","spots":[{"key":"p:莎蓮娜魔法大學裡面","place":"莎蓮娜 魔法大學裡面","kind":"unique","minutes":null,"coords":[33,167]}]},
        {"key":"herb/茴香","name":"茴香","level":9,"fee4000":18200,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":671},{"key":"p:米內葛爾島坎那貝拉村南門外","place":"米內葛爾島 坎那貝拉村南門外","kind":"spot","minutes":663,"coords":[615,389],"nav":true}]},
        {"key":"herb/七葉樹","name":"七葉樹","level":10,"fee4000":40000,"hint":null,"spots":[{"key":"shed","place":"素材屋","kind":"shed","minutes":1348},{"key":"p:庫魯克斯島米諾基亞鎮東門外","place":"庫魯克斯島 米諾基亞鎮東門外","kind":"spot","minutes":1487,"coords":[613,723],"nav":true}]}
      ]}
    ]
  };
  root.STARCG_GATHER_DATA = data;
  if (typeof module !== 'undefined' && module.exports) module.exports = data;
})(typeof window !== 'undefined' ? window : globalThis);
